apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  storageClassName: ebs-dynamic # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi

---

apiVersion: v1
kind: Pod
metadata:
 name: nginx-pod
 labels:
  purpose: ebs-dynamic-demo
spec:
 nodeSelector:
  topology.kubernetes.io/zone: us-east-1b
 containers:
 - name: nginx-demo
   image: nginx
   volumeMounts:
   - name: nginx-storage
     mountPath: /usr/share/nginx/html

 volumes:
 - name: nginx-storage
   persistentVolumeClaim:
    claimName: ebs-dynamic

---

apiVersion: v1
kind: Service
metadata:
 name: nginx-service
 labels:
  purpose: ebs-dynamic-demo-service
spec:
 type: LoadBalancer
 selector:
   purpose: ebs-dynamic-demo
 ports:
 - protocol: TCP
   port: 80
   targetPort: 80