apiVersion: v1
kind: PersistantVolume
metadata:
 name: efs-static
 labels:
  purpose: efs-satic-demo
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-018a24fe769f4807b
  
---

apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
 name: efs-static
 labels:
  purpose: efs-static-demo
spec:
 volumeName: efs-static
 accessModes:
 - ReadWriteOnce
 resources:
  requests: 
   storage: 5Gi

--- 

apiVersion: v1
kind: Pod
metadata:
 name: efs-pod
 labels:
  purpose: efs-satic-demo
spec:
 containers:
 - name: nginx-efs
   image: nginx
   volumeMounts:
   - name: efs-static
   mountPath: /usr/share/nginx/html

 volumes:
 - name: efs-static
   persistentVolumeClaim:
    claimName: efs-static

---

apiVersion: v1 
kind: Service
metadata:
 name: efs-static
spec:
 type: LoadBalancer
 selector:
  purpose: efs-satic-demo
 ports:
 - protocol: TCP
   port: 80
   targetPort: 80



