apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
 name: efs-dynamic
 labels:
  purpose: efs-dynamic-demo
spec:
 storageClassName: efs-sc
 accessModes:
 - ReadWriteOnce
 resources:
  requests: 
   storage: 5Gi

--- 

apiVersion: v1
kind: Pod
metadata:
 name: efs-pod
 labels:
  purpose: efs-dynamic-demo
spec:
 containers:
 - name: nginx-efs
   image: nginx
   volumeMounts:
   - name: efs-dynamic
     mountPath: /usr/share/nginx/html

 volumes:
 - name: efs-dynamic
   persistentVolumeClaim:
    claimName: efs-dynamic

---

apiVersion: v1 
kind: Service
metadata:
 name: efs-dynamic
spec:
 type: LoadBalancer
 selector:
  purpose: efs-dynamic-demo
 ports:
 - protocol: TCP
   port: 80
   targetPort: 80