apiVersion: v1
kind: Pod
metadata:
 name: resource-limit 
 labels:
  purpose: demo
spec:
 containers:
 - name: nginx
   image: nginx
   resources:
    requests: 
     memory: "68mi"
     cpu: "100"
    limits:
     memory: "128mi"
     cpu: "150mi"