apiVersion: v1
kind: Pod
metadata:
 name: env-pod
 labels:
  purpose: env-demo
spec:
 containers:
 - name: env-pod
   image: nginx
   env:
   - name: COURSE
     value: "kubernetes"
   - name: TRAINER
     value: "siva"