apiVersion: v1
kind: Secret
metadata:
 name: pod-secret
type: Opaque
data:
 USERNAME: "YWpheQo="
 PASSWORD: "QWpheTEyMwo="

---

apiVersion: v1
kind: Pod
metadata:
 name: pod-secret
spec:
 containers:
 - name: configmap-demo
   image: nginx
   envFrom:
   - SecretRef:
      name: pod-secret
