apiVersion: v1
kind: Service
metadata:
 name: service-lb
 labels:
  purpose: service-lb-demo
spec:
 type: LoadBalancer
 selector:
  project: roboshop
  env: dev
 ports:
 - protocol: TCP
   port: 80
   targetPort: 80

---
# apiVersion: v1
# kind: Pod
# metadata:
#  name: pod-lb
#  labels:
#   project: roboshop
#   env: dev
# spec: 
#  containers:
#  - name: lb-pod
#    image: nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: deployment-nginx
 labels:
  project: roboshop
  env: dev
spec:
 replicas: 2
 selector:
  matchLabels:
   project: roboshop
   env: dev
 template:
  metadata:
   labels:
    project: roboshop
    env: dev
  spec:
   containers:
   - name: nginx-dp
     image: nginx
   
  
