apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: replicaset
 labels:
  purpose: replicaset-demo
spec:
 replicas: 3
 selector:
  matchlabes:
   project: roboshop
   env: dev
template:
 metadata:
  labels:
   project: roboshop
   env: dev
 spec:
  containers:
  - name: nginx
    image: nginx
