apiVersion: apps/v1
kind: Deployment
metadata:
 name: deployment-nginx
 labels:
  project: roboshop
  env: dev
spec:
 replicas: 2
 selector:
  matchLabels:
   project: roboshop
   env: dev
 template:
  metadata:
   labels:
    project: roboshop
    env: dev
  spec:
   containers:
   - name: nginx-dp
     image: nginx
   
  
