# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#  name: statefulset-pvc
#  labels:
#   purpose: statefulset-demo
# spec:
#  storageClassName: ebs-dynamic
#  accessModes:
#  - ReadWriteOnce
#  resources:
#   requests:
#     storage: 5Gi

---

# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#  name: statefulset-pod
#  labels:
#   purpose: statefulset-demo
# spec:
#  replicas: 3
#  serviceName: "headless-svc"
#  selector:
#   matchLabels:
#    purpose: statefulset-demo
#  template:
#   metadata:
#    labels:
#     purpose: statefulset-demo
#   spec:
#    containers:
#    - name: nginx
#      image: nginx
#      volumeMounts:
#      - name: ebs-provisioner
#        mountPath: /usr/share/nginx/html

#   volumeClaimTemplates:
#   - metadata:
#       name: statefulset-pvc
#     spec:
#       accessModes: [ "ReadWriteOnce" ]
#       storageClassName: "ebs-dynamic"
#       resources:
#         requests:
#           storage: 1Gi

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-pod
spec:
  selector:
    matchLabels:
      purpose: statefulset-demo # has to match .spec.template.metadata.labels
  serviceName: "headless-svc"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        purpose: statefulset-demo # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: statefulset-pvc
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: statefulset-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-dynamic"
      resources:
        requests:
          storage: 1Gi

--- 

apiVersion: v1 
kind: Service
metadata: 
 name: headless-svc
 labels:
  purpose: statefulset-demo
spec:
 clusterIP: None
 selector:
  purpose: statefulset-demo
 ports:
 - port: 80
   name: web
 

---
apiVersion: v1 
kind: Service
metadata: 
 name: nginx-cip
 labels:
  purpose: statefulset-demo
spec:
 selector:
  purpose: statefulset-demo
 ports:
 - protocol: TCP
   port: 80
   targetPort: 80

   
