apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: statefulset-pvc
 labels:
  purpose: statefulset-demo
spec:
 storageClassName: ebs-dynamic
 accessModes:
 - ReadWriteOnce
 resources:
  requests:
    storage: 5Gi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: statefulset-pod
 labels:
  purpose: statefulset-demo
spec:
 replicas: 3
 serviceName: "headless-svc"
 selector:
  matchLabels:
   purpose: statefulset-demo
 template:
  metadata:
   labels:
    purpose: statefulset-demo
  spec:
   containers:
   - name: nginx
     image: nginx
     volumeMounts:
     - name: ebs-provisioner
       mountPath: /usr/share/nginx/html
   volumes:
   - name: ebs-provisioner
     persistentVolumeClaim:
      claimName: statefulset-pvc

--- 

apiVersion: v1 
kind: Service
metadata: 
 name: headless-svc
 labels:
  purpose: statefulset-demo
spec:
 clusterIP: None
 selector:
  purpose: statefulset-demo
 ports:
 - port: 80
   name: web
 

---
apiVersion: v1 
kind: Service
metadata: 
 name: nginx-cip
 labels:
  purpose: statefulset-demo
spec:
 selector:
  purpose: statefulset-demo
 ports:
 - protocol: TCP
   port: 80
   targetPort: 80

   
